### PR TITLE
AV review

### PR DESCRIPTION
**Pull request by AndreaVolkamer**
## Description
Feedback on maxsmi repo and functionality.

## Todos
  - [x] Check readme
  - [x]  Installation works
  - [x] Examples/predictions run
  - [x] Check code
  - [x] Check [documentation](https://maxsmi.readthedocs.io/en/latest)
  - [x]  Check result analysis notebooks

## Questions
- [ ] xxxx

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by AndreaVolkamer** [comment]
@t-kimber Really nice repo!!!

I added a few adaptions when trying out the proposed examples.
... Note, still waiting for two of the examples (2 & 3) to finish running ....

**Comment by AndreaVolkamer** [comment]
@t-kimber I added a suggestion for a textual description of the project
* feel free to edit it
* and please add the bullet points for used augmentation strategies, data sets, and models

**Comment by AndreaVolkamer** [comment]
@t-kimber one point that would be nice to add is a description of the content (code, input, output files) of the repo, to help navigate the repo for newbies
* Where to find/or how to collect the input data
* Where are the precalculated models or the generated outputs stored
* Where the analysis nbs can be found

Maybe similar to [this overview](https://github.com/volkamerlab/kissim_app/blob/master/README.md), but potentially less detailed (restricted to mention those of most interest for the user).

**Comment by AndreaVolkamer** [comment]
@t-kimber the docs look great. I added 
* only small textual edits
* title for the project
* a fix for the results files sorting which is different on my laptop/system (in prediction nb)
* and added showing some lines of the log file (in prediction nb)

**Comment by AndreaVolkamer** [comment]
Running full_workflow.py
* I really like the logging info!
* Additionally, it would be nice if the user gets a bit more info while the script is being executed (main steps (data retrieval, model building, some result summary), and where the generated information is stored?)
* And some error/warning info, i.e. if the user tries to run an option that is not available (e.g. typo in the task), the user could be informed on the console. Not only in the log file: ‘WARNING:root:Invalid data. Choosing ESOL by default.’
* And could the help text also include the available choices (e.g. which tasks) and the chosen defaults?

**Comment by AndreaVolkamer** [comment]
@t-kimber the code looks very organized, great doc strings!

One suggestion to make the repo even easier to understand for newbies: 
how about we add subfolders in the code (maxsmi) folder, e.g. for all utils (nicely named `utils_[task].py`), ml related (`pytorch_[task].py`)?

**Comment by AndreaVolkamer** [comment]
@t-kimber the following analysis notebooks do not run due to missing input files.

* results_ensemble_learning_vs_canonical.ipynb
`[Errno 2] No such file or directory: '/home/andrea/devel/py/maxsmi/maxsmi/output_/ESOL_smiles_augmentation_with_reduced_duplication_70_no_augmentation_0_CONV1D/results_ensemble_learning.pkl'`
* results_maxsmi_EGFR.ipynb
`[Errno 2] No such file or directory: '/home/andrea/devel/py/maxsmi/maxsmi/output/affinity_smiles_augmentation_with_reduced_duplication_70_augmentation_with_reduced_duplication_70_CONV1D/results_metrics.pkl'`
-> note here it looks actually in `output` not `output_`, but in both I think the affinity data is still missing.
* results_plot.ipynb and results_tables.ipynb don't run because of missing input, the y do contain a warning at the beginning.  Just wondering, what exactly would be needed? Are those files too large to include them? Or what would be the instructions to include them? 
> The notebook will not run unless all simulations have been stored in the output folder.

In that regard also the question: `output` is used for new user output, and `output_` stores the precalculated data? Maybe we rename the second to make that more clear?

**Comment by AndreaVolkamer** [comment]
Regarding `results_canonical_vs_random.ipynb`
* Note on top, we also need the same for the augmentation by 1 model, right? can you add the respective command line call as well?
* I added a small analysis of the prediction error difference, check if you like it.

**Comment by AndreaVolkamer** [comment]
Tiny comment on `results_ensemble_learning_confidence_vs_rmse.ipynb`

In the second part you nicely comment on the 'without duplication' fact to avoid biasing. Maybe just add a small comment that for esol and lipo the maxsmi models are with(_reduced)_duplication.

**Comment by t-kimber** [comment]
> @t-kimber Really nice repo!!!
> 
> I added a few adaptions when trying out the proposed examples.
> ... Note, still waiting for two of the examples (2 & 3) to finish running ....
> 
> Update to this comment (15.09): all examples finished now after reducing the number of epochs to 5, should we adapt this number in the examples to make them run faster, or add a note that it might run relatively long.

I've added a warning so that people know that training the model with 250 epochs will take time.

**Comment by t-kimber** [comment]
> @t-kimber I added a suggestion for a textual description of the project, feel free to edit it

I fixed a few things here and there.

**Comment by t-kimber** [comment]
> @t-kimber one point that would be nice to add is a description of the content (code, input, output files) of the repo, to help navigate the repo for newbies
> 
> * Where to find/or how to collect the input data
> * Where are the precalculated models or the generated outputs stored
> * Where the analysis nbs can be found
> 
> Maybe similar to [this overview](https://github.com/volkamerlab/kissim_app/blob/master/README.md), but potentially less detailed (restricted to mention those of most interest for the user).

I added a repo structure section, I hope it makes it easier to navigate through the folders.

**Comment by t-kimber** [comment]
> @t-kimber the docs look great. I added
> 
> * only small textual edits
> * title for the project
> * a fix for the results files sorting which is different on my laptop/system (in prediction nb)
> * and added showing some lines of the log file (in prediction nb)
> 
> Lastly one question: There is an API documentation tab, but no info in it, am I missing sth or can we take it out?

I fixed some typos, checked the HTML rendering locally, and removed the API tab. The documentation should be ready to go :)

**Comment by t-kimber** [comment]
> @t-kimber Great example scripts.
> 
> Concerning `full_workflow.py`:
> 
> * I really like the logging info!
> * Additionally, it would be nice if the user gets a bit more info while the script is being executed (main steps (data retrieval, model building, some result summary), and where the generated information is stored?)
> * And some error/warning info, i.e. if the user tries to run an option that is not available (e.g. typo in the task), the user could be informed on the console. Not only in the log file: ‘WARNING:root:Invalid data. Choosing ESOL by default.’
> * And could the help text also include the available choices (e.g. which tasks) and the chosen defaults?

The reason nothing is printed in the terminal (no print statements, only logging info) is because this script was created to run on a GPU, and Jaime told me it's better to use logging than printing.

**Comment by t-kimber** [comment]
> @t-kimber the following analysis notebooks do not run due to missing input files.
> 
> * results_ensemble_learning_vs_canonical.ipynb
>   `[Errno 2] No such file or directory: '/home/andrea/devel/py/maxsmi/maxsmi/output_/ESOL_smiles_augmentation_with_reduced_duplication_70_no_augmentation_0_CONV1D/results_ensemble_learning.pkl'`
> * results_maxsmi_EGFR.ipynb
>   `[Errno 2] No such file or directory: '/home/andrea/devel/py/maxsmi/maxsmi/output/affinity_smiles_augmentation_with_reduced_duplication_70_augmentation_with_reduced_duplication_70_CONV1D/results_metrics.pkl'`
>   -> note here it looks actually in `output` not `output_`, but in both I think the affinity data is still missing.
> * results_plot.ipynb and results_tables.ipynb don't run because of missing input, the y do contain a warning at the beginning.  Just wondering, what exactly would be needed? Are those files too large to include them? Or what would be the instructions to include them?
> 
> > The notebook will not run unless all simulations have been stored in the output folder.
> 
> In that regard also the question: `output` is used for new user output, and `output_` stores the precalculated data? Maybe we rename the second to make that more clear?

These notebooks should now run.
>Just wondering, what exactly would be needed? Are those files too large to include them? 
Yes, uploading all the results would exceed the memory available on github.

**Comment by t-kimber** [comment]
> Regarding `results_canonical_vs_random.ipynb`
> 
> * Note on top, we also need the same for the augmentation by 1 model, right? can you add the respective command line call as well?
> * I added a small analysis of the prediction error difference, check if you like it.

I made a few changes so that the notebook would run until the end even if lipo or free solv are selected . I also added the necessary command line (note that since the random smiles is random, the results might differ a tiny bit if someone ran them locally.)

**Comment by t-kimber** [comment]
> Tiny comment on `results_ensemble_learning_confidence_vs_rmse.ipynb`
> 
> In the second part you nicely comment on the 'without duplication' fact to avoid biasing. Maybe just add a small comment that for esol and lipo the maxsmi models are with(_reduced)_duplication.
> 
> Very nice analysis notebooks!

Done! :)

**Review by t-kimber — APPROVED** [review]
All looks good !

**Pull request merged**
